### ISSUE TITLE
Auto-fill parameters based on pixel size/imaging conditions

### ISSUE THREAD

**Issue by thebigsban** [focolab/gcamp-extractor#10]

**Comment by RaymondDunn** [comment]
eh. good idea in principle but like, basically all of of our recordings are taken under the same objective and imaging conditions. there's too much variability across individuals to meaningfully set automatic params. I contend that default static params lead to more predictable behavior, and can be easily tuned using functionality already provided in gce.

closing for convenience, someone feel free to reopen if you like this
