### ISSUE TITLE
feature: trace grid labels can be updated with arbitrary text

### ISSUE THREAD

**Issue by Borchardt** [focolab/gcamp-extractor#25]
purpose: allow labeling of neurons within tool. user labels should be saved to output json

**Comment by RaymondDunn** [comment]
@Borchardt does GCE as it stands allow for modifying neuron labels in curator?

**Comment by Borchardt** [comment]
Yep! This is done, at least as originally intended. Labels updated in the curator don't get propagated outside of `curate.json`, but any work for that should happen in #44.
