### ISSUE TITLE
consolidate TiffReader (wb-utils) and MultiFIleTiff (this repo)

### ISSUE THREAD

**Issue by gregbubnis** [focolab/gcamp-extractor#32]
These classes have highly overlapping functionality that should (IMO) be consolidated. One lazy reader class should be adequate for all of our tiff-formatted image data (NeuroPAL, gcamp, etc..).

**Comment by RaymondDunn** [comment]
@gregbubnis I'm going through longstanding github issues, could you advise on the status of this?

**Comment by gregbubnis** [comment]
I'd say that the discussion stalled out and I am not sure how best to
orchestrate the merger. There is obv a lot of duplicate functionality but
this doesn't seem to be scientifically rate limiting so low priority IMO
