### ISSUE TITLE
Confusing argument syntax for gaussian2d and gaussian3d

### ISSUE THREAD

**Issue by gregbubnis** [focolab/gcamp-extractor#34]
I just looked more carefully at the gaussian2d and gaussian3d functions. In my opinion, the argument formatting requirements are confusing and cluttered with dimension name conventions. There might even be contradictions between the function descriptions and what the code does. Since the segfunctions module is shaping up to be the lab's go-to collection of filtering tools I suggest we fix it sooner rather than later.

So, it would be a breaking change, but would changing the calling syntax to something like the following make sense?

```
def gaussian3d(x, width=None, sigma=None):
```
where ```x``` is the data array and ```width``` and ```sigma``` are either scalars (isotropic case) or lists/tuples that match the dimension order of ```x```.

Thoughts?

**Comment by RaymondDunn** [comment]
totally agree with the sentiment. iirc, segfunctions module continued to be built out more. @gregbubnis did you already make these changes?

**Comment by gregbubnis** [comment]
Thanks for jumping in here Ray.

I didn't change anything.

Also, I think this code migrated to the image processing repo.

Having just re-read the code, my subjective opinion is that these functions
are not really adding any functionality on top of the cv2 functions. It is
more like a minefield of conditionals and ninja defaults between the user
and the raw cv2 functions.

sk-image has an ND gaussian blur that could probably replace both of these.
It decomposes ND into a series of 1D steps, as Steven did originally, and
it will automatically compute a kernel size based on the standard
deviations (which would cut down on parameters).

https://scikit-image.org/docs/dev/api/skimage.filters.html#skimage.filters.gaussian

So I'd suggest deprecating these but open to keeping them if they are doing
something I'm not aware of.

**Comment by RaymondDunn** [comment]
yeah good catch i was super surprised to see that by default, both gaussian_2d/3d does:
 ```
    width_x = width_y = 19
    width_z = 5
    sigma_x = sigma_y = 6
    sigma_z = 1
```
which gets updated in the event of input args which specifically are tuples, and arranged a specific sequence... this feels way more likely to promote errors than normal kwargs. the same can be said about medFilt2d and medFilt3d. i agree with deprecating these wrappers in favor of the native functions

**Comment by gregbubnis** [comment]
Duplicate of an issue now on the image-processing repo
