### ISSUE TITLE
Extractor params `gaussian` and `anisotropy` do not survive json export import

### ISSUE THREAD

**Issue by gregbubnis** [focolab/gcamp-extractor#35]
1. The default parameters for `Extractor` include tuples `anisotropy` and `gaussian`.
2. Gaussian filtering functions in segfunctions.py only accept `gaussian` filter widths as tuples (lists get ignored)
3. Tuples do not survive json export/import -- they are exported to, and imported as, a list.

Therefore, reloaded `Extractor` params will silently get ignored if used for gaussian filtering.

I realized this when seeing that re-running a gaussian filtering step in a bfd pipeline gave different results the second time (after parameters were json exported/imported).

I will make sure that `gaussian2d` and `gaussian3d` only receive tuples from my end, but it might be worth allowing lists as well as tuples.

**Comment by RaymondDunn** [comment]
totally agree here. has this been updated already? i think your observation in #34 might obviate this, i'm a fan of your suggestion to replace those wrapper functions of gaussian2d and gaussian3d with the native library calls. w/r/t anisotropy, i don't see a call like `isinstance(args[0],tuple)` so i don't think that's as much of a problem. 

if you agree we could close this and reference it in #34?

**Comment by gregbubnis** [comment]
Not updated and I'm on board with that suggestion, Ray.
