### ISSUE TITLE
seed peakfinding with initial neuron locations for neuropal timeseries extraction

### ISSUE THREAD

**Issue by RaymondDunn** [focolab/gcamp-extractor#40]
currently, using a tool like greg's np-gui, you can perform peak detection and labeling on neuropal structural images.
to quantify timeseries based on the output of that tool, currently GCE implements:
* take initial positions of neurons
* adjust neuron positions based on calculated global motion if param `register == True`

however due to local warping or underestimated global motion, especially present in long recordings, it would be exceedingly useful to continue to seek and update neuron positions based on pixel data. ideally this should leverage all the peakfinding infrastructure present, but in effect "seed" peakfinding at timepoint t=-1.

**Comment by Borchardt** [comment]
Believed solved by commit https://github.com/focolab/gcamp-extractor/commit/b318436c3d933f442ef334edbc78f4fd8b7929cf and, separately, by commit https://github.com/focolab/gcamp-extractor/commit/4829af4435b322fe9972f4f3898dacddd3c0b28a. @RaymondDunn can you confirm and close or update?

**Comment by RaymondDunn** [comment]
testing later today!

**Comment by RaymondDunn** [comment]
closing cause we forgot to close this once tests looked pretty good
