### ISSUE TITLE
Merging blob threads - across Z planes

### ISSUE THREAD

**Issue by thebigsban** [focolab/gcamp-extractor#9]

**Comment by RaymondDunn** [comment]
iirc there's no actual merging of rois across z currently implemented
instead there's
* 3d peakfinding so peaks shouldn't match adjactent z's
* quantification voxel excludes masks from other neurons, e.g. nearby neuron on adjactent z-plane

is marge across z important? perhaps if we were to segment on individual z-planes, then merge (like wb-matlab algorithm). But 3d peak finding seems pretty good! so I suggest we close this for now for cleanliness, then reopen a new issue when the use case arises

closing now for convenience assuming that's kewl
